//! Applications and the remote face: the identity model, composition,
//! invocation profiles, resources, the one global interaction contract, the
//! carrier vocabularies, and the ingress paved road.
//!
//! # One contract, projected
//!
//! The global interaction contract is stated ONCE, independent of who plays
//! which role; client, server, session, and carrier surfaces are PROJECTIONS
//! generated by the macros crate (hosts opt in via features), and a
//! projection may not add, drop, reorder, relabel, or weaken any message,
//! refusal, cancellation transition, flow-control state, or completion
//! outcome — a projection that diverges is a defect, not a dialect, and no
//! projection becomes its own only judge. "Serve" is dead as a package and
//! survives only as prose for the remote face; the old type prefix died with
//! it.
//!
//! # The final law (carried verbatim in substance)
//!
//! Paths grant no authority. Packaging grants no authority. Artifact
//! placement grants no authority. Carrier security grants no capability.
//! Routing grants no partition authority. Delivery order is not durable
//! history order. Push is not recovery truth. A disconnect is not
//! nonexecution. A generated client is not a second protocol. An adapter is
//! not semantic architecture.

use crate::history::RemovalCommitment;
use crate::identity::{
    AuthorityPosition, ByteIdentity, Commitment, CreationLaw, IdentityClass, IdentityRole,
    Occurrence,
};
use crate::types::EvidenceRef;

// ---------------------------------------------------------------------------
// The local identity model.
// ---------------------------------------------------------------------------

/// Application-meaning domain marker.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct AppMeaningDomain;

/// Answers "same meaning?" — never "same bytes?"; built only by semantic
/// normalization of an admitted declaration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct AppSemanticCommitment(pub Commitment<AppMeaningDomain>);

/// The byte-role marker for application-image bytes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct AppImageByteRole;

/// Proves byte equality ALONE — never semantic equivalence, interface
/// compatibility, admission, authenticity, capability, availability, or
/// live-instance identity; supplying one identity where another is required
/// is a wrong-role refusal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct AppImageDigest(pub ByteIdentity<AppImageByteRole>);

/// The claim marker for application-image references.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct AppImageClaim;

/// A five-part reference (role + identity + version + availability +
/// integrity, riding the root evidence-reference shape) — a digest-shaped
/// value with no declared role is not a lawful reference.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AppImageRef(pub EvidenceRef<AppImageClaim>);

/// Interface-commitment domain marker.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InterfaceDomain;

/// Every fact a caller must rely on — anything that changes a caller's
/// lawful inputs, outputs, authority, effects, bounds, refusals, or evidence
/// participates; packaging metadata, source maps, and qualification
/// references may change without silently claiming an interface change. It
/// identifies NO bytes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InterfaceCommitment(pub Commitment<InterfaceDomain>);

/// The identity role marker for live instances.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InstanceRole;

/// One live coordination binding — Class D, minted only by admitted
/// activation. It steals no ownership: the runtime still owns process state
/// and checkpoints; the membrane still owns Attempts and reservations;
/// backends still own durability. Live capability authority cannot be
/// serialized out of an instance as a bearer token.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InstanceId(Occurrence<InstanceRole>);

impl IdentityRole for InstanceId {
    const CLASS: IdentityClass = IdentityClass::Occurrence;
    const CREATION: CreationLaw = CreationLaw::FreshOpaque;
}

impl InstanceId {
    /// In-crate mint for laws. Test-gated until activation minting exists.
    #[cfg(test)]
    pub(crate) const fn for_laws(occurrence: Occurrence<InstanceRole>) -> Self {
        Self(occurrence)
    }
}

/// One activation generation — Class C, scoped to its instance, carrying
/// scope and order ONLY (no image identity in the scope bytes): an image
/// upgrade is one reason the generation order advances, and generations stay
/// ordered across it.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ActivationGeneration(pub AuthorityPosition<InstanceId>);

/// Which image a generation activated — an auxiliary fact riding a typed
/// relation, never the ordinal's bytes.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ActivationImageBinding {
    /// The generation.
    pub generation: ActivationGeneration,
    /// The activated image.
    pub image: AppImageRef,
}

/// The identity role marker for entrypoints.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct EntrypointRole;

/// One exported entrypoint — binds exact program images; a request cannot
/// substitute a foreign program while keeping the entrypoint's authority.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct EntrypointId(Occurrence<EntrypointRole>);

impl IdentityRole for EntrypointId {
    const CLASS: IdentityClass = IdentityClass::Occurrence;
    const CREATION: CreationLaw = CreationLaw::FreshOpaque;
}

/// The six non-identities: supplying any of these where an application
/// generation is required is a wrong-role refusal.
pub const NON_IDENTITIES: [&str; 6] = [
    "route-name",
    "process-name",
    "host-name",
    "connection-id",
    "path-string",
    "package-name",
];

// ---------------------------------------------------------------------------
// Composition and lifecycle.
// ---------------------------------------------------------------------------

/// The instance lifecycle — durable and recoverable (a runtime state machine
/// plus persisted data); no transition leaves `Retired`; wrong-order,
/// wrong-generation, or foreign input yields a typed refusal, never a silent
/// drop or panic. Activation admits a live generation of an immutable image
/// without mutating it — a route update activates no authority; upgrade
/// closes every relationship BEFORE the new generation accepts work;
/// rollback erases no accepted facts and revives no retired generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InstanceLifecycle {
    /// Instantiated.
    Instantiated,
    /// Active.
    Active,
    /// Draining — overlapping active and draining generations preserve exact
    /// generation binding.
    Draining,
    /// Retired — terminal.
    Retired,
}

/// The application-linking validation ladder — affine typestate, statically
/// owned; `Admissible` is terminal. (The application image is used ONLY when
/// persistent composition genuinely requires it — never a universal wrapper,
/// never a requirement for the four boundary forms; the linker is a pure
/// closed-world function whose input-permutation invariance is law.)
pub const APPLICATION_VALIDATION_LADDER: [&str; 5] = [
    "untrusted-bytes",
    "bounded-decoded",
    "semantically-linked",
    "independently-reconstructed",
    "admissible",
];

// ---------------------------------------------------------------------------
// Invocation profiles and resources.
// ---------------------------------------------------------------------------

/// The three complete invocation profiles — typed configuration; unsupported
/// or contradictory combinations refuse rather than silently degrading. All
/// three execute through IDENTICAL executor semantics, differing only in
/// composition authority, lifetime, permissible effects, grant origin,
/// generation binding, and evidence role. Given the same pure program,
/// parameters, selectors, cuts, bounds, and profiles, the three produce
/// equivalent semantic values — an independent oracle, not an implementation
/// assertion — yet equivalent values never make their receipts
/// interchangeable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InvocationProfile {
    /// A caller-supplied or locally selected validated program, bounded
    /// one-shot — no application image, instance, or generation implied.
    DirectProgram,
    /// One admitted application interface and one live generation.
    ApplicationEntrypoint,
    /// A caller-supplied canonical PURE program under a separately admitted
    /// read-only query grant — effect refusal derived from the semantic
    /// effect posture, never a hand-maintained blacklist; a computed
    /// allow/deny/defer stays data and cannot perform an effect.
    RestrictedQuery,
}

/// Resource-reference domain marker.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ResourceDomain;

/// A typed resource reference: typed identity plus declared rights and
/// generation constraints — knowing, guessing, receiving, or listing a path
/// grants NO authority; a resolved reference grants no access and proves no
/// freshness.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ResourceRef(pub Commitment<ResourceDomain>);

/// What a resource reference never silently becomes.
pub const RESOURCE_NEVER_BECOMES: [&str; 8] = [
    "a-host-path",
    "a-live-file-descriptor",
    "a-bearer-capability",
    "a-secret-or-raw-key",
    "a-durable-checkpoint",
    "an-accepted-event",
    "a-datablock-authority-claim",
    "an-external-service-identity",
];

// ---------------------------------------------------------------------------
// The remote face: the contract and the carrier vocabularies.
// ---------------------------------------------------------------------------

/// The six fixed components of the one global interaction contract.
pub const CONTRACT_COMPONENTS: [&str; 6] = [
    "complete-message-alphabet",
    "admissible-orderings",
    "refusal-algebra",
    "cancellation-semantics",
    "flow-control-credit-law",
    "completion-and-reopening-rule",
];

/// The sixteen message families — derived from real operations, never a
/// generic RPC template.
pub const MESSAGE_FAMILIES: [&str; 16] = [
    "negotiation",
    "profile-bound-negotiation",
    "authentication-and-possession-proof",
    "grant-presentation-refresh",
    "request-admission",
    "the-three-invocations",
    "result-refusal-uncertainty-evidence-carriage",
    "stream-lifecycle",
    "cancellation-and-observer-abandonment",
    "session-drain-and-terminal-close",
    "ephemeral-continuation",
    "durable-resumption-claim",
    "checkpoint-proposal-and-admitted-acknowledgement",
    "lag-overrun-recovery-replay",
    "route-and-partition-epoch-claims",
    "carrier-fallback",
];

/// The nine facts every message family states.
pub const FAMILY_FACTS: [&str; 9] = [
    "which-states-can-receive-it",
    "identity-and-correlation-requirements",
    "semantic-owner",
    "bounds",
    "replayability",
    "admission-or-observation-only",
    "evidence-carried",
    "terminal-refusal-set",
    "exact-protocol-version",
];

/// Transport-security claim marker — what a carrier can carry evidence
/// ABOUT, never a truth it may establish.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TransportSecurityClaim;

/// Identity-possession claim marker — what a carrier can carry evidence
/// ABOUT, never a truth it may establish.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct PossessionClaim;

/// The nine adapter-supplied observations the sans-I/O core consumes — all
/// host obligations; the core itself reads NOTHING directly (no carrier,
/// clock, entropy, artifact store, environment, credential store, or async
/// executor).
///
/// Two observations carry EVIDENCE rather than a verdict: a carrier never
/// mints semantic truth by announcing that something is "verified". It hands
/// over a typed reference to the claim it observed; the security and
/// admission owners interpret that evidence and decide what, if anything,
/// follows. (Variant names pending review.)
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum CarrierObservation {
    /// Bytes received.
    BytesReceived,
    /// Bytes accepted for write.
    BytesAcceptedForWrite,
    /// Flow-control availability.
    FlowControlAvailability,
    /// Connection opened, half-closed, or closed.
    ConnectionTransition,
    /// Evidence about the carrier's transport security, carried for the
    /// security owner to interpret.
    TransportSecurityEvidence(EvidenceRef<TransportSecurityClaim>),
    /// Evidence about identity possession on the carrier, carried for the
    /// admission owner to interpret.
    PossessionEvidence(EvidenceRef<PossessionClaim>),
    /// An idle threshold.
    IdleThreshold,
    /// An absolute deadline reached (the host's own clock domain — no
    /// monotonic transplant).
    AbsoluteDeadlineReached,
    /// A carrier retry.
    CarrierRetry,
}

/// The identity role marker for carrier requests.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct CarrierRequestRole;

/// Correlates protocol messages on a carrier — NOT the logical operation,
/// the Turn, an idempotency identity, an Attempt, or the membrane's port
/// request; they relate only through typed carriage, and matching raw bits
/// never lets one satisfy the other. The remote face mints no Turn or
/// Attempt as a transport convenience.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct CarrierRequestId(Occurrence<CarrierRequestRole>);

impl IdentityRole for CarrierRequestId {
    const CLASS: IdentityClass = IdentityClass::Occurrence;
    const CREATION: CreationLaw = CreationLaw::FreshOpaque;
}

impl CarrierRequestId {
    /// In-crate mint for laws. Test-gated until the protocol core exists.
    #[cfg(test)]
    pub(crate) const fn for_laws(occurrence: Occurrence<CarrierRequestRole>) -> Self {
        Self(occurrence)
    }
}

/// The identity role marker for sessions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SessionRole;

/// One negotiated protocol lifetime — NOT a durable subscription, a
/// checkpoint, a user identity, a capability grant, a source cut, or an
/// application generation. A session can die while the durable subscription
/// and checkpoint survive; session identity alone can neither validate nor
/// invalidate durable progress.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SessionId(Occurrence<SessionRole>);

impl IdentityRole for SessionId {
    const CLASS: IdentityClass = IdentityClass::Occurrence;
    const CREATION: CreationLaw = CreationLaw::FreshOpaque;
}

impl SessionId {
    /// In-crate mint for laws. Test-gated until negotiation exists.
    #[cfg(test)]
    pub(crate) const fn for_laws(occurrence: Occurrence<SessionRole>) -> Self {
        Self(occurrence)
    }
}

/// The session-direction fact itself — never a guarantee profile.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DeliveryDirection {
    /// Sending.
    Send,
    /// Receiving.
    Receive,
}

/// Orders delivery within one session direction — NOT the authority
/// sequence, a commit point, a cursor, a checkpoint, a Turn, an HLC, or
/// federation progress.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct DeliveryIndex {
    /// The session.
    pub session: SessionId,
    /// The direction.
    pub direction: DeliveryDirection,
    /// The ordinal within that scope.
    pub index: u64,
}

/// The session's terminal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SessionTerminal {
    /// An orderly close.
    OrderlyClose,
    /// Physical death.
    PhysicalDeath,
}

/// The session state — advances sequentially; terminal reached through
/// draining or directly on physical death, and no transition leaves it. A
/// message no current state may lawfully receive is a typed refusal, never a
/// silent drop or panic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SessionState {
    /// Pre-negotiation.
    PreNegotiation,
    /// Negotiated.
    Negotiated,
    /// Draining.
    Draining,
    /// Terminated.
    Terminated(SessionTerminal),
}

/// One direction half's state — a half-closed half is a direction state,
/// NOT a stream terminal; "local-half-closed"/"remote-half-closed" are
/// renderings of which half closed, never third states. Closing one
/// direction never closes the other.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DirectionState {
    /// Open.
    Open,
    /// Half-closed.
    HalfClosed,
}

/// The separate whole-stream closure fact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StreamClosure {
    /// Open.
    Open,
    /// Closed.
    Closed,
    /// Reset.
    Reset,
}

/// The stream state — a record of both halves plus the closure fact, NOT
/// one linear half-close enum. Whole-stream terminal requires the direction
/// closures the profile makes relevant plus terminal evidence, or an
/// explicit reset.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct StreamState {
    /// The send half.
    pub send: DirectionState,
    /// The receive half.
    pub receive: DirectionState,
    /// The whole-stream closure.
    pub closure: StreamClosure,
}

/// The delivery guarantee — AUTHORED rename (the old spelling collided with
/// the runtime home's delivery-role enum; one spelling, one meaning). The
/// remote face never calls transport delivery exactly-once: effectively-once
/// application behavior requires stable logical and effect-intent
/// identities, durable admission, and idempotency at the owning boundary — a
/// transport sequence number cannot provide it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DeliveryGuarantee {
    /// Ephemeral; loss, duplication, and gaps per carrier; no durable
    /// resumability.
    BestEffort,
    /// Compatible sessions resume admitted progress; redelivery lawful and
    /// visible; skipping accepted history forbidden. Requires a durable
    /// acknowledged checkpoint.
    ResumableAtLeastOnce,
}

/// The four non-interchangeable flow-control facts — a slow consumer forces
/// no unbounded buffering, retained push state, unbounded replay history, or
/// hidden work.
pub const FLOW_CONTROL_FACTS: [&str; 4] = [
    "carrier-writability",
    "protocol-credit",
    "application-capacity",
    "durable-progress",
];

/// Lag/overrun claim markers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NotRetainedClaim;
/// Recovery-path claim marker.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct RecoveryPathClaim;
/// Continuation-posture domain marker.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ContinuationPostureDomain2;

/// A typed lag/overrun observation: what was no longer retained, which
/// recovery path remains, whether the profile can continue — never silently
/// skipping accepted history.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct LagOverrunObservation {
    /// What was no longer retained.
    pub not_retained: EvidenceRef<NotRetainedClaim>,
    /// The remaining recovery path.
    pub recovery: EvidenceRef<RecoveryPathClaim>,
    /// Whether the profile can continue.
    pub continuation: Commitment<ContinuationPostureDomain2>,
}

/// The typed in-stream removal hole: when a resumable stream serves material
/// that was authorizedly removed or shredded, the hole carries the history
/// home's removal outcome — the delivery index NEVER runs contiguously over
/// an invisible gap, because a peer that cannot detect a hole even in
/// principle has been served a silently edited history.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct RemovalHole {
    /// The removal's commitment.
    pub removal: RemovalCommitment,
}

/// The eight non-substitutable preimages — none can substitute for any
/// exact source cut or durable checkpoint; opaque does not mean trusted, and
/// any transplant across source, lineage, generation, query, selector,
/// direction, principal, application generation, partition epoch, or
/// checkpoint family refuses.
pub const NON_SUBSTITUTABLE_PREIMAGES: [&str; 8] = [
    "hlc",
    "wall-time",
    "route",
    "page-number",
    "result-count",
    "push-notice",
    "session-id",
    "delivery-index",
];

// ---------------------------------------------------------------------------
// The ingress paved road (the standing decision, baked).
// ---------------------------------------------------------------------------

/// The eight ingress pipeline stages.
pub const INGRESS_PIPELINE: [&str; 8] = [
    "many-physical-producers",
    "bounded-carrier-input",
    "typed-message-claim",
    "protocol-authentication-replay-role-validation",
    "application-owned-decode-and-semantic-transformation",
    "capability-policy-authority-admission",
    "one-accepted-local-publication-under-region-and-epoch",
    "later-turns-and-derived-materializations-at-exact-cuts",
];

/// The progressive acknowledgement ladder — one honest signal per stage.
/// `received` and `validated` are progress/latency evidence only; ONLY
/// `admitted` (durably in accepted ingress history, crash-survivable)
/// discharges the sender's retry duty. The wire handshake is a projection of
/// the server's durable per-claim ingress progress record, so a crash is
/// traceable to the last durably recorded stage. An admitted ingress event
/// establishes receipt of the claim and its provenance, not the truth of the
/// domain assertion carried inside it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IngressAck {
    /// Framed, not yet validated.
    Received,
    /// Protocol/authentication/replay/role/firewall checks passed, not yet
    /// durable.
    Validated,
    /// Durably in accepted ingress history — the only retry discharge.
    Admitted,
}

/// The ack profile — NO paved-road default: the deep handshake and the
/// admitted-only single ack are equally safe because the discharge invariant
/// holds identically in both (a symmetric, safety-equivalent tradeoff earns
/// no default — the interface selects). `SingleAck` means ADMITTED-ONLY,
/// never received or validated, or a retry could infer a stronger stage than
/// was durably reached.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AckProfile {
    /// The three-stage handshake.
    ThreeStageHandshake,
    /// One admitted-only acknowledgement.
    SingleAck,
}

/// The idempotency identity ladder — established in this preference order,
/// safe by default. Whether two byte-identical requests are one retry or two
/// intents is CLIENT INTENT, unrecoverable from content: no server-side
/// content hash may dedupe effectful ingress. The reservation token is
/// idempotency-safe ONLY when obtained through an idempotent reserve keyed
/// by a stable client nonce (repeating it recovers the SAME token — a token
/// returned only on an acknowledgement the client may never receive cannot
/// rescue the retry that needs it; this is the only lawful reservation-token
/// story). SDK keys are one per intended OPERATION INSTANCE, never per
/// source-code call site. EFFECTFUL OR STATE-CHANGING INGRESS PRESENTING
/// NONE OF THESE IS REFUSED.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IdempotencyIdentity {
    /// A natural business key the operation already carries.
    NaturalKey,
    /// A reservation token via idempotent nonce-keyed reserve.
    ClientNonceReservationToken,
    /// An SDK- or generated-client-minted stable key per operation instance.
    SdkMintedKey,
    /// An explicit client key.
    ExplicitClientKey,
}

impl IdempotencyIdentity {
    /// The declared preference ladder.
    pub const LADDER: [Self; 4] = [
        Self::NaturalKey,
        Self::ClientNonceReservationToken,
        Self::SdkMintedKey,
        Self::ExplicitClientKey,
    ];
}

/// The rejected-content reason classes. Default: a typed redacted
/// diagnostic (stage failed, bounded redacted observations, a KEYED
/// scope-bound content fingerprint — never a public unkeyed digest — and the
/// exact failed check), redacted by classification so it leaks no secret.
/// Raw retention is per-reason-class OPT-IN under the four guardrails. The
/// retention windows and per-class capture are marked deployment tunables,
/// not product decisions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RejectedContentReason {
    /// Malformed.
    Malformed,
    /// Unauthorized.
    Unauthorized,
    /// Over budget.
    OverBudget,
    /// Failed classification.
    FailedClassification,
}

/// The four non-negotiable raw-retention guardrails.
pub const RAW_RETENTION_GUARDRAILS: [&str; 4] = [
    "bounded-size-count-age",
    "expiring-with-secure-deletion",
    "access-controlled-to-audit-roles",
    "never-re-admittable",
];

/// The thirteen authentication/identity/admission roles that never merge —
/// several may resolve to one principal without becoming one
/// interchangeable identity; authentication is not authorization is not
/// information release. Credential or bearer material never enters receipts,
/// logs, explanations, generated clients, artifacts, push payloads, or
/// error text.
pub const AUTH_ROLES: [&str; 13] = [
    "carrier-confidentiality",
    "represented-subject",
    "immediate-actor",
    "client-device",
    "delegate",
    "peer-claim",
    "proof-of-possession",
    "credential-validity",
    "capability-claim",
    "admitted-grant",
    "operation-admission",
    "physical-observation",
    "receipt",
];

/// What replayable carrier early data carries NONE of — and no carrier,
/// intermediary, retry, reconnect, or fallback can silently resubmit an
/// effectful operation under a new logical identity.
pub const EARLY_DATA_NEVER: [&str; 8] = [
    "an-effectful-invocation",
    "event-or-effect-intent-admission",
    "checkpoint-advancement",
    "durable-progress-acknowledgement",
    "grant-creation-attenuation-revocation",
    "secret-mutation",
    "application-activation",
    "partition-epoch-mutation",
];

/// The ordinary local model's eight nouns.
pub const LOCAL_NOUNS: [&str; 8] = [
    "program",
    "application",
    "entrypoint",
    "resource",
    "port",
    "capability",
    "result",
    "receipt",
];

/// The ordinary remote model's eight verbs.
pub const REMOTE_VERBS: [&str; 8] = [
    "connect",
    "authenticate",
    "invoke",
    "receive",
    "open-a-bounded-stream",
    "acknowledge-or-checkpoint-under-the-correct-owner",
    "resume-from-durable-progress",
    "stop-waiting-without-lying-about-admitted-work",
];
